name: CI - MediTrack Backend

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:

  # ============================================================
  # ETAPA 1: COMPILACIÓN
  # ============================================================
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Descargar código del repositorio
        uses: actions/checkout@v4

      - name: Configurar Java
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: maven

      - name: Compilar proyecto
        run: mvn package -DskipTests

  # ============================================================
  # ETAPA 2: PRUEBAS AUTOMATIZADAS
  # ============================================================
  test:
    runs-on: ubuntu-latest
    needs: build

    steps:
      - name: Descargar código del repositorio
        uses: actions/checkout@v4

      - name: Configurar Java
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: maven

      - name: Ejecutar pruebas automatizadas
        run: mvn test

  # ============================================================
  # ETAPA 3: DESPLIEGUE SIMULADO
  # ============================================================
  deploy:
    runs-on: ubuntu-latest
    needs: test

    steps:
      - name: Descargar código del repositorio
        uses: actions/checkout@v4

      - name: Crear carpeta release
        run: |
          mkdir -p release
          cp -r src release/

      - name: Confirmar despliegue
        run: echo "Despliegue exitoso"